require('dotenv').config({ path: require('path').join(__dirname, '../.env') });
// fallback check for root .env when run from root
require('dotenv').config({ path: require('path').join(__dirname, '../../.env') });

const mongoose = require('mongoose');
const College = require('../models/College');

const colleges = [
  {
    name: 'IIT Madras',
    type: 'IIT',
    nirfRank: 1,
    city: 'Chennai',
    state: 'Tamil Nadu',
    admissionMode: 'JEE Advanced',
    feesPerYear: 220000,
    cutoffRankCSE: '~250',
    avgPlacement: 21.5,
    highestPlacement: 180.0,
    description: 'Indian Institute of Technology Madras is a public technical university located in Chennai, Tamil Nadu. It is consistently ranked as the top engineering institute in India by NIRF and is recognized as an Institute of Eminence.',
    website: 'https://www.iitm.ac.in',
    branches: ['Computer Science Engineering', 'Electrical Engineering', 'Mechanical Engineering', 'Chemical Engineering', 'Aerospace Engineering', 'Civil Engineering']
  },
  {
    name: 'IIT Delhi',
    type: 'IIT',
    nirfRank: 2,
    city: 'New Delhi',
    state: 'Delhi',
    admissionMode: 'JEE Advanced',
    feesPerYear: 225000,
    cutoffRankCSE: '~150',
    avgPlacement: 22.2,
    highestPlacement: 210.0,
    description: 'Indian Institute of Technology Delhi is a premier public research university located in New Delhi. It offers highly competitive engineering programs and has a world-renowned entrepreneurship and research ecosystem.',
    website: 'https://home.iitd.ac.in',
    branches: ['Computer Science Engineering', 'Electrical Engineering', 'Mechanical Engineering', 'Chemical Engineering', 'Biotechnology', 'Textile Technology']
  },
  {
    name: 'IIT Bombay',
    type: 'IIT',
    nirfRank: 3,
    city: 'Mumbai',
    state: 'Maharashtra',
    admissionMode: 'JEE Advanced',
    feesPerYear: 230000,
    cutoffRankCSE: '~100',
    avgPlacement: 23.5,
    highestPlacement: 233.0,
    description: 'Indian Institute of Technology Bombay is a prestigious technical university located in Powai, Mumbai. It is famous for its computer science department, campus life, and pioneering role in startup incubation.',
    website: 'https://www.iitb.ac.in',
    branches: ['Computer Science Engineering', 'Electrical Engineering', 'Mechanical Engineering', 'Aerospace Engineering', 'Metallurgical Engineering', 'Chemical Engineering']
  },
  {
    name: 'IIT Kanpur',
    type: 'IIT',
    nirfRank: 4,
    city: 'Kanpur',
    state: 'Uttar Pradesh',
    admissionMode: 'JEE Advanced',
    feesPerYear: 215000,
    cutoffRankCSE: '~500',
    avgPlacement: 19.3,
    highestPlacement: 152.0,
    description: 'Indian Institute of Technology Kanpur is a public research university located in Kanpur, Uttar Pradesh. It is known for its academic rigor, strong science and research focus, and expansive green campus.',
    website: 'https://www.iitk.ac.in',
    branches: ['Computer Science Engineering', 'Electrical Engineering', 'Mechanical Engineering', 'Materials Science', 'Aerospace Engineering', 'Chemical Engineering']
  },
  {
    name: 'IIT Roorkee',
    type: 'IIT',
    nirfRank: 5,
    city: 'Roorkee',
    state: 'Uttarakhand',
    admissionMode: 'JEE Advanced',
    feesPerYear: 222000,
    cutoffRankCSE: '~1500',
    avgPlacement: 17.5,
    highestPlacement: 120.0,
    description: 'Indian Institute of Technology Roorkee (formerly University of Roorkee and Thomason College of Civil Engineering) is the oldest technical institution in Asia, renowned for its strong alumni network and civil engineering history.',
    website: 'https://www.iitr.ac.in',
    branches: ['Computer Science Engineering', 'Electronics & Communication Engineering', 'Civil Engineering', 'Electrical Engineering', 'Mechanical Engineering', 'Chemical Engineering']
  },
  {
    name: 'IIT Kharagpur',
    type: 'IIT',
    nirfRank: 6,
    city: 'Kharagpur',
    state: 'West Bengal',
    admissionMode: 'JEE Advanced',
    feesPerYear: 220000,
    cutoffRankCSE: '~700',
    avgPlacement: 18.1,
    highestPlacement: 140.0,
    description: 'Indian Institute of Technology Kharagpur is the first IIT established in India. It has the largest campus area and the highest student enrollment, offering a massive variety of engineering and interdisciplinary courses.',
    website: 'https://www.iitkgp.ac.in',
    branches: ['Computer Science Engineering', 'Electronics & Electrical Communication', 'Mechanical Engineering', 'Ocean Engineering', 'Mining Engineering', 'Agricultural Engineering']
  },
  {
    name: 'IIT Guwahati',
    type: 'IIT',
    nirfRank: 7,
    city: 'Guwahati',
    state: 'Assam',
    admissionMode: 'JEE Advanced',
    feesPerYear: 220000,
    cutoffRankCSE: '~2000',
    avgPlacement: 16.5,
    highestPlacement: 102.0,
    description: 'Indian Institute of Technology Guwahati is a public research university established in Assam. Located on the banks of the Brahmaputra River, it is known for having one of the most beautiful university campuses in India.',
    website: 'https://www.iitg.ac.in',
    branches: ['Computer Science Engineering', 'Electronics & Electrical Engineering', 'Mechanical Engineering', 'Chemical Science & Technology', 'Biotechnology']
  },
  {
    name: 'IIT Hyderabad',
    type: 'IIT',
    nirfRank: 8,
    city: 'Sangareddy',
    state: 'Telangana',
    admissionMode: 'JEE Advanced',
    feesPerYear: 225000,
    cutoffRankCSE: '~2500',
    avgPlacement: 16.8,
    highestPlacement: 80.0,
    description: 'Indian Institute of Technology Hyderabad is a second-generation IIT known for its strong ties with Japanese universities, state-of-the-art infrastructure, and rapid rise in research rankings.',
    website: 'https://www.iith.ac.in',
    branches: ['Computer Science Engineering', 'Electrical Engineering', 'Mechanical & Aerospace Engineering', 'Biomedical Engineering', 'Materials Science & Metallurgical']
  },
  {
    name: 'NIT Trichy',
    type: 'NIT',
    nirfRank: 9,
    city: 'Tiruchirappalli',
    state: 'Tamil Nadu',
    admissionMode: 'JEE Mains',
    feesPerYear: 145000,
    cutoffRankCSE: '~5000',
    avgPlacement: 12.5,
    highestPlacement: 54.0,
    description: 'National Institute of Technology Tiruchirappalli is a public technical university. It is consistently ranked as the top NIT in India, offering excellent placements and an active student culture.',
    website: 'https://www.nitt.edu',
    branches: ['Computer Science Engineering', 'Electronics & Communication Engineering', 'Electrical & Electronics Engineering', 'Mechanical Engineering', 'Production Engineering', 'Chemical Engineering']
  },
  {
    name: 'Jadavpur University',
    type: 'State',
    nirfRank: 10,
    city: 'Kolkata',
    state: 'West Bengal',
    admissionMode: 'WBJEE',
    feesPerYear: 10000,
    cutoffRankCSE: '~100',
    avgPlacement: 11.2,
    highestPlacement: 85.0,
    description: 'Jadavpur University is a premier public state university located in Kolkata. It is famous for its extremely low fee structure (highly subsidized) and exceptionally strong placements in CSE and IT.',
    website: 'http://www.jaduniv.edu.in',
    branches: ['Computer Science Engineering', 'Information Technology', 'Electronics & Telecommunication', 'Electrical Engineering', 'Mechanical Engineering', 'Power Engineering']
  },
  {
    name: 'VIT Vellore',
    type: 'VIT',
    nirfRank: 11,
    city: 'Vellore',
    state: 'Tamil Nadu',
    admissionMode: 'VITEEE',
    feesPerYear: 198000,
    cutoffRankCSE: '~5000 (Rank)',
    avgPlacement: 7.8,
    highestPlacement: 44.0,
    description: 'Vellore Institute of Technology is a private university located in Vellore, Tamil Nadu. It is ranked as one of the top private engineering schools and features a massive student intake with solid placement records.',
    website: 'https://vit.ac.in',
    branches: ['Computer Science Engineering', 'Information Technology', 'Electronics & Communication Engineering', 'Electrical & Electronics Engineering', 'Mechanical Engineering', 'Biotechnology']
  },
  {
    name: 'NIT Surathkal',
    type: 'NIT',
    nirfRank: 12,
    city: 'Surathkal',
    state: 'Karnataka',
    admissionMode: 'JEE Mains',
    feesPerYear: 150000,
    cutoffRankCSE: '~6000',
    avgPlacement: 12.1,
    highestPlacement: 55.0,
    description: 'National Institute of Technology Karnataka, also known as NITK Surathkal, is located on a beachside campus in Mangaluru. It is highly sought after for its placements, academic curriculum, and beach campus.',
    website: 'https://www.nitk.ac.in',
    branches: ['Computer Science Engineering', 'Information Technology', 'Electronics & Communication Engineering', 'Mechanical Engineering', 'Mining Engineering', 'Metallurgical Engineering']
  },
  {
    name: 'Anna University',
    type: 'State',
    nirfRank: 13,
    city: 'Chennai',
    state: 'Tamil Nadu',
    admissionMode: 'TNEA',
    feesPerYear: 55000,
    cutoffRankCSE: '~1200',
    avgPlacement: 6.0,
    highestPlacement: 42.0,
    description: 'Anna University is a premier public state university in Tamil Nadu. The main campus (CEG Guindy and MIT Chromepet) is renowned for providing quality education at affordable costs and producing industry-ready graduates.',
    website: 'https://www.annauniv.edu',
    branches: ['Computer Science Engineering', 'Electronics & Communication Engineering', 'Information Technology', 'Mechanical Engineering', 'Electrical & Electronics Engineering']
  },
  {
    name: 'IIT Indore',
    type: 'IIT',
    nirfRank: 14,
    city: 'Indore',
    state: 'Madhya Pradesh',
    admissionMode: 'JEE Advanced',
    feesPerYear: 220000,
    cutoffRankCSE: '~4000',
    avgPlacement: 14.5,
    highestPlacement: 70.0,
    description: 'Indian Institute of Technology Indore is one of the second-generation IITs. It features a modern campus, high citation counts in research, and outstanding coding environments.',
    website: 'https://www.iiti.ac.in',
    branches: ['Computer Science Engineering', 'Electrical Engineering', 'Mechanical Engineering', 'Civil Engineering', 'Metallurgical Engineering & Materials Science']
  },
  {
    name: 'IIT BHU Varanasi',
    type: 'IIT',
    nirfRank: 15,
    city: 'Varanasi',
    state: 'Uttar Pradesh',
    admissionMode: 'JEE Advanced',
    feesPerYear: 220000,
    cutoffRankCSE: '~3000',
    avgPlacement: 16.2,
    highestPlacement: 120.0,
    description: 'Indian Institute of Technology (BHU) Varanasi is a public technical university located in Varanasi. Formerly IT-BHU, it is located within the historic Banaras Hindu University campus and has a strong legacy.',
    website: 'https://iitbhu.ac.in',
    branches: ['Computer Science Engineering', 'Electronics Engineering', 'Electrical Engineering', 'Mechanical Engineering', 'Chemical Engineering', 'Ceramic Engineering']
  },
  {
    name: 'ICT Mumbai',
    type: 'State',
    nirfRank: 16,
    city: 'Mumbai',
    state: 'Maharashtra',
    admissionMode: 'MHT-CET / JEE Mains',
    feesPerYear: 85200,
    cutoffRankCSE: '~1000',
    avgPlacement: 8.0,
    highestPlacement: 35.0,
    description: 'Institute of Chemical Technology is a premier state-funded university in Mumbai focused on chemical engineering, pharmacy, and materials sciences. It is renowned globally for its research output.',
    website: 'https://www.ictmumbai.edu.in',
    branches: ['Chemical Engineering', 'Dyestuff Technology', 'Polymer Engineering', 'Food Engineering', 'Pharmaceutical Technology']
  },
  {
    name: 'IIT ISM Dhanbad',
    type: 'IIT',
    nirfRank: 17,
    city: 'Dhanbad',
    state: 'Jharkhand',
    admissionMode: 'JEE Advanced',
    feesPerYear: 220000,
    cutoffRankCSE: '~5000',
    avgPlacement: 14.2,
    highestPlacement: 120.0,
    description: 'Indian Institute of Technology (Indian School of Mines) Dhanbad is a premier public university. It is historically famous for earth sciences and mining engineering and was upgraded to an IIT in 2016.',
    website: 'https://www.iitism.ac.in',
    branches: ['Computer Science Engineering', 'Electronics & Communication Engineering', 'Electrical Engineering', 'Mining Engineering', 'Petroleum Engineering', 'Mechanical Engineering']
  },
  {
    name: 'NIT Rourkela',
    type: 'NIT',
    nirfRank: 18,
    city: 'Rourkela',
    state: 'Odisha',
    admissionMode: 'JEE Mains',
    feesPerYear: 140000,
    cutoffRankCSE: '~8000',
    avgPlacement: 10.2,
    highestPlacement: 45.0,
    description: 'National Institute of Technology Rourkela is a premier technical institution funded by the Government of India. It has one of the largest campus areas in the country with modern laboratories.',
    website: 'https://www.nitrkl.ac.in',
    branches: ['Computer Science Engineering', 'Electronics & Communication Engineering', 'Electrical Engineering', 'Mechanical Engineering', 'Chemical Engineering', 'Biotechnology']
  },
  {
    name: 'Amrita Vishwa Vidyapeetham',
    type: 'Private',
    nirfRank: 19,
    city: 'Coimbatore',
    state: 'Tamil Nadu',
    admissionMode: 'AEEE / JEE Mains',
    feesPerYear: 250000,
    cutoffRankCSE: '~5000',
    avgPlacement: 7.5,
    highestPlacement: 56.8,
    description: 'Amrita School of Engineering provides multi-disciplinary education. It features high research output and holds a strong value-oriented educational environment.',
    website: 'https://www.amrita.edu',
    branches: ['Computer Science Engineering', 'Artificial Intelligence', 'Electronics & Communication', 'Mechanical Engineering', 'Electrical & Computer Engineering']
  },
  {
    name: 'Thapar Institute (TIET)',
    type: 'Private',
    nirfRank: 20,
    city: 'Patiala',
    state: 'Punjab',
    admissionMode: 'JEE Mains',
    feesPerYear: 450000,
    cutoffRankCSE: '~15000',
    avgPlacement: 10.5,
    highestPlacement: 40.0,
    description: 'Thapar Institute of Engineering and Technology is a prestigious private deemed-to-be-university. It is famous for its active placement cell, state-of-the-art campus facilities, and tie-up with Trinity College Dublin.',
    website: 'https://www.thapar.edu',
    branches: ['Computer Science Engineering', 'Computer Engineering', 'Electronics & Communication Engineering', 'Electrical Engineering', 'Mechanical Engineering', 'Biotechnology']
  },
  {
    name: 'NIT Warangal',
    type: 'NIT',
    nirfRank: 21,
    city: 'Warangal',
    state: 'Telangana',
    admissionMode: 'JEE Mains',
    feesPerYear: 145000,
    cutoffRankCSE: '~4000',
    avgPlacement: 13.5,
    highestPlacement: 88.0,
    description: 'National Institute of Technology Warangal is highly regarded for its rigorous academic curriculum and exceptional coding culture, drawing top IT companies to its campus placement drives.',
    website: 'https://www.nitw.ac.in',
    branches: ['Computer Science Engineering', 'Electronics & Communication', 'Electrical & Electronics', 'Mechanical Engineering', 'Chemical Engineering', 'Metallurgical Engineering']
  },
  {
    name: 'IIT Ropar',
    type: 'IIT',
    nirfRank: 22,
    city: 'Rupnagar',
    state: 'Punjab',
    admissionMode: 'JEE Advanced',
    feesPerYear: 220000,
    cutoffRankCSE: '~5500',
    avgPlacement: 15.1,
    highestPlacement: 85.0,
    description: 'Indian Institute of Technology Ropar is a second-generation IIT that has quickly established a name in research and engineering excellence in northern India.',
    website: 'https://www.iitrpr.ac.in',
    branches: ['Computer Science Engineering', 'Electrical Engineering', 'Mechanical Engineering', 'Chemical Engineering', 'Civil Engineering']
  },
  {
    name: 'IIT Gandhinagar',
    type: 'IIT',
    nirfRank: 23,
    city: 'Gandhinagar',
    state: 'Gujarat',
    admissionMode: 'JEE Advanced',
    feesPerYear: 225000,
    cutoffRankCSE: '~4500',
    avgPlacement: 15.3,
    highestPlacement: 90.0,
    description: 'Indian Institute of Technology Gandhinagar is known for its highly flexible curriculum, international collaborations, and beautiful campus situated along the Sabarmati river.',
    website: 'https://iitgn.ac.in',
    branches: ['Computer Science Engineering', 'Electrical Engineering', 'Mechanical Engineering', 'Chemical Engineering', 'Materials Engineering']
  },
  {
    name: 'NIT Calicut',
    type: 'NIT',
    nirfRank: 24,
    city: 'Kozhikode',
    state: 'Kerala',
    admissionMode: 'JEE Mains',
    feesPerYear: 145000,
    cutoffRankCSE: '~7000',
    avgPlacement: 11.5,
    highestPlacement: 47.0,
    description: 'National Institute of Technology Calicut is a premier institute located in Kerala, known for its lush green campus, strong research focus, and excellent campus placements in core and software profiles.',
    website: 'http://www.nitc.ac.in',
    branches: ['Computer Science Engineering', 'Electronics & Communication', 'Electrical & Electronics', 'Mechanical Engineering', 'Civil Engineering', 'Chemical Engineering']
  },
  {
    name: 'BITS Pilani',
    type: 'BITS',
    nirfRank: 25,
    city: 'Pilani',
    state: 'Rajasthan',
    admissionMode: 'BITSAT',
    feesPerYear: 520000,
    cutoffRankCSE: '~300 (Score)',
    avgPlacement: 15.8,
    highestPlacement: 110.0,
    description: 'Birla Institute of Technology & Science, Pilani is a premier private university in India. Known for its zero-attendance policy, practice school internships, and high-quality peers, it is widely considered on par with top IITs.',
    website: 'https://www.bits-pilani.ac.in',
    branches: ['Computer Science Engineering', 'Electrical & Electronics Engineering', 'Electronics & Instrumentation Engineering', 'Mechanical Engineering', 'Chemical Engineering', 'Civil Engineering']
  },
  {
    name: 'Jamia Millia Islamia',
    type: 'State',
    nirfRank: 26,
    city: 'New Delhi',
    state: 'Delhi',
    admissionMode: 'JEE Mains',
    feesPerYear: 20000,
    cutoffRankCSE: '~15000',
    avgPlacement: 9.0,
    highestPlacement: 35.0,
    description: 'Jamia Millia Islamia is a central university in Delhi offering highly affordable engineering education with competitive placement packages.',
    website: 'https://www.jmi.ac.in',
    branches: ['Computer Engineering', 'Electronics & Communication', 'Electrical Engineering', 'Mechanical Engineering', 'Civil Engineering']
  },
  {
    name: 'BITS Mesra',
    type: 'Private',
    nirfRank: 27,
    city: 'Ranchi',
    state: 'Jharkhand',
    admissionMode: 'JEE Mains',
    feesPerYear: 280000,
    cutoffRankCSE: '~20000',
    avgPlacement: 9.5,
    highestPlacement: 58.0,
    description: 'Birla Institute of Technology, Mesra is a highly reputed deemed university located in Ranchi, offering a wide array of engineering specializations and a legacy of notable alumni.',
    website: 'https://www.bitmesra.ac.in',
    branches: ['Computer Science Engineering', 'Electronics & Communication', 'Electrical & Electronics', 'Mechanical Engineering', 'Information Technology']
  },
  {
    name: 'SRM Institute (KTR)',
    type: 'Private',
    nirfRank: 28,
    city: 'Kattankulathur',
    state: 'Tamil Nadu',
    admissionMode: 'SRMJEE',
    feesPerYear: 250000,
    cutoffRankCSE: '~8000 (Rank)',
    avgPlacement: 7.5,
    highestPlacement: 41.0,
    description: 'SRM Institute of Science and Technology is a private deemed university located near Chennai. It features a large global campus and holds excellent ties with tech companies for placement drives.',
    website: 'https://www.srmist.edu.in',
    branches: ['Computer Science Engineering', 'Information Technology', 'Electronics & Communication Engineering', 'Biotechnology', 'Mechanical Engineering']
  },
  {
    name: 'DTU Delhi',
    type: 'State',
    nirfRank: 29,
    city: 'New Delhi',
    state: 'Delhi',
    admissionMode: 'JEE Mains',
    feesPerYear: 219000,
    cutoffRankCSE: '~10000',
    avgPlacement: 15.2,
    highestPlacement: 64.0,
    description: 'Delhi Technological University (formerly Delhi College of Engineering) is a public state university. It is highly reputed for engineering in Delhi, featuring a massive campus and outstanding packages for tech roles.',
    website: 'https://dtu.ac.in',
    branches: ['Computer Science Engineering', 'Information Technology', 'Software Engineering', 'Electronics & Communication Engineering', 'Mechanical Engineering', 'Electrical Engineering']
  },
  {
    name: 'IIT Jodhpur',
    type: 'IIT',
    nirfRank: 30,
    city: 'Jodhpur',
    state: 'Rajasthan',
    admissionMode: 'JEE Advanced',
    feesPerYear: 220000,
    cutoffRankCSE: '~6000',
    avgPlacement: 13.0,
    highestPlacement: 61.0,
    description: 'Indian Institute of Technology Jodhpur is an institute of national importance that emphasizes interdisciplinary research, artificial intelligence, and futuristic technology courses.',
    website: 'https://www.iitj.ac.in',
    branches: ['Computer Science Engineering', 'Electrical Engineering', 'Mechanical Engineering', 'Bioengineering', 'Materials Engineering']
  },
  {
    name: 'IIT Patna',
    type: 'IIT',
    nirfRank: 31,
    city: 'Patna',
    state: 'Bihar',
    admissionMode: 'JEE Advanced',
    feesPerYear: 220000,
    cutoffRankCSE: '~5500',
    avgPlacement: 14.0,
    highestPlacement: 60.0,
    description: 'Indian Institute of Technology Patna is an Institute of National Importance established in 2008. It has developed strong academic partnerships and offers great core and IT sector placements.',
    website: 'https://www.iitp.ac.in',
    branches: ['Computer Science Engineering', 'Electrical Engineering', 'Mechanical Engineering', 'Chemical Engineering', 'Civil Engineering']
  },
  {
    name: 'IIT Bhubaneswar',
    type: 'IIT',
    nirfRank: 32,
    city: 'Bhubaneswar',
    state: 'Odisha',
    admissionMode: 'JEE Advanced',
    feesPerYear: 220000,
    cutoffRankCSE: '~7000',
    avgPlacement: 13.5,
    highestPlacement: 56.0,
    description: 'Indian Institute of Technology Bhubaneswar operates from a permanent campus at Argul, offering an excellent environment for study and research with a state-of-the-art computing setup.',
    website: 'https://www.iitbbs.ac.in',
    branches: ['Computer Science Engineering', 'Electrical Engineering', 'Electronics & Communication', 'Mechanical Engineering', 'Civil Engineering']
  },
  {
    name: 'IIT Mandi',
    type: 'IIT',
    nirfRank: 33,
    city: 'Mandi',
    state: 'Himachal Pradesh',
    admissionMode: 'JEE Advanced',
    feesPerYear: 220000,
    cutoffRankCSE: '~8000',
    avgPlacement: 12.8,
    highestPlacement: 50.0,
    description: 'Indian Institute of Technology Mandi is nestled in the picturesque Himalayas. It is known for its unique project-oriented design curriculum and strong focus on eco-friendly technology solutions.',
    website: 'https://www.iitmandi.ac.in',
    branches: ['Computer Science Engineering', 'Electrical Engineering', 'Mechanical Engineering', 'Data Science & Engineering', 'Bioengineering']
  },
  {
    name: 'VNIT Nagpur',
    type: 'NIT',
    nirfRank: 34,
    city: 'Nagpur',
    state: 'Maharashtra',
    admissionMode: 'JEE Mains',
    feesPerYear: 145000,
    cutoffRankCSE: '~9000',
    avgPlacement: 10.5,
    highestPlacement: 42.0,
    description: 'Visvesvaraya National Institute of Technology Nagpur is a premier NIT located in Maharashtra, featuring a rich academic heritage and excellent student placement statistics.',
    website: 'https://www.vnit.ac.in',
    branches: ['Computer Science Engineering', 'Electronics & Communication', 'Electrical & Electronics', 'Mechanical Engineering', 'Civil Engineering', 'Chemical Engineering']
  },
  {
    name: "Siksha 'O' Anusandhan",
    type: 'Private',
    nirfRank: 35,
    city: 'Bhubaneswar',
    state: 'Odisha',
    admissionMode: 'SAAT / JEE Mains',
    feesPerYear: 235000,
    cutoffRankCSE: '~45000',
    avgPlacement: 6.5,
    highestPlacement: 31.0,
    description: 'Siksha O Anusandhan is a deemed university in Bhubaneswar, Odisha. It is popular for its high-tech infrastructure and strong industry alignments for placements.',
    website: 'https://www.soa.ac.in',
    branches: ['Computer Science Engineering', 'Information Technology', 'Electronics & Communication', 'Electrical Engineering', 'Mechanical Engineering']
  },
  {
    name: 'Aligarh Muslim University',
    type: 'State',
    nirfRank: 36,
    city: 'Aligarh',
    state: 'Uttar Pradesh',
    admissionMode: 'AMUEEE',
    feesPerYear: 25000,
    cutoffRankCSE: '~2500',
    avgPlacement: 5.8,
    highestPlacement: 21.0,
    description: 'Zakir Husain College of Engineering and Technology, a constituent college of AMU, has a legacy of engineering excellence and highly subsidized fees.',
    website: 'https://www.amu.ac.in',
    branches: ['Computer Engineering', 'Electronics Engineering', 'Electrical Engineering', 'Mechanical Engineering', 'Civil Engineering']
  },
  {
    name: 'SVNIT Surat',
    type: 'NIT',
    nirfRank: 37,
    city: 'Surat',
    state: 'Gujarat',
    admissionMode: 'JEE Mains',
    feesPerYear: 145000,
    cutoffRankCSE: '~11000',
    avgPlacement: 9.8,
    highestPlacement: 44.0,
    description: 'Sardar Vallabhbhai National Institute of Technology Surat is located in the diamond and textile hub of Gujarat, offering top quality industry research and internships.',
    website: 'https://www.svnit.ac.in',
    branches: ['Computer Science Engineering', 'Electronics & Communication', 'Electrical Engineering', 'Mechanical Engineering', 'Chemical Engineering', 'Civil Engineering']
  },
  {
    name: 'MNNIT Allahabad',
    type: 'NIT',
    nirfRank: 38,
    city: 'Prayagraj',
    state: 'Uttar Pradesh',
    admissionMode: 'JEE Mains',
    feesPerYear: 145000,
    cutoffRankCSE: '~6000',
    avgPlacement: 12.8,
    highestPlacement: 118.0,
    description: 'Motilal Nehru National Institute of Technology Allahabad is highly renowned for its computer science placements, competitive programming environment, and historic legacy.',
    website: 'http://www.mnnit.ac.in',
    branches: ['Computer Science Engineering', 'Electronics & Communication', 'Electrical Engineering', 'Mechanical Engineering', 'Information Technology', 'Chemical Engineering']
  },
  {
    name: 'SASTRA University',
    type: 'Private',
    nirfRank: 39,
    city: 'Thanjavur',
    state: 'Tamil Nadu',
    admissionMode: 'JEE Mains + Boards',
    feesPerYear: 160000,
    cutoffRankCSE: '~15000',
    avgPlacement: 7.0,
    highestPlacement: 32.0,
    description: 'SASTRA Deemed University is a leading private institution in Tamil Nadu, recognized for high academic standards, active research labs, and recruiting partnerships.',
    website: 'https://www.sastra.edu',
    branches: ['Computer Science Engineering', 'Information Technology', 'Electronics & Communication', 'Mechanical Engineering', 'Bioengineering']
  },
  {
    name: 'KIIT Bhubaneswar',
    type: 'Private',
    nirfRank: 40,
    city: 'Bhubaneswar',
    state: 'Odisha',
    admissionMode: 'KIITEE',
    feesPerYear: 350000,
    cutoffRankCSE: '~20000',
    avgPlacement: 8.2,
    highestPlacement: 63.0,
    description: 'Kalinga Institute of Industrial Technology is a prominent private university in Odisha, famous for its grand infrastructure, diverse student body, and 100% placement record.',
    website: 'https://kiit.ac.in',
    branches: ['Computer Science Engineering', 'Information Technology', 'Electronics & Communication', 'Electrical Engineering', 'Mechanical Engineering', 'Aerospace Engineering']
  },
  {
    name: 'IIEST Shibpur',
    type: 'State',
    nirfRank: 41,
    city: 'Shibpur',
    state: 'West Bengal',
    admissionMode: 'JEE Mains',
    feesPerYear: 135000,
    cutoffRankCSE: '~15000',
    avgPlacement: 8.8,
    highestPlacement: 39.0,
    description: 'Indian Institute of Engineering Science and Technology Shibpur is one of the oldest technical colleges in India, boasting a heritage of engineering contributions.',
    website: 'https://www.iiests.ac.in',
    branches: ['Computer Science Engineering', 'Electronics & Telecommunication', 'Electrical Engineering', 'Mechanical Engineering', 'Civil Engineering', 'Mining Engineering']
  },
  {
    name: 'Kalasalingam Academy',
    type: 'Private',
    nirfRank: 42,
    city: 'Krishnankoil',
    state: 'Tamil Nadu',
    admissionMode: 'KEEE / Merit',
    feesPerYear: 120000,
    cutoffRankCSE: '~50000',
    avgPlacement: 4.8,
    highestPlacement: 30.0,
    description: 'Kalasalingam Academy of Research and Education is a private university in south India that provides technology courses focused on practical, hands-on learning.',
    website: 'https://www.kalasalingam.ac.in',
    branches: ['Computer Science Engineering', 'Information Technology', 'Electronics & Communication', 'Electrical & Electronics', 'Mechanical Engineering']
  },
  {
    name: 'SSN College of Engineering',
    type: 'Private',
    nirfRank: 43,
    city: 'Chennai',
    state: 'Tamil Nadu',
    admissionMode: 'TNEA / Merit',
    feesPerYear: 125000,
    cutoffRankCSE: '~5000',
    avgPlacement: 7.2,
    highestPlacement: 40.0,
    description: 'Sri Sivasubramaniya Nadar College of Engineering, founded by Shiv Nadar of HCL, is a highly reputed college affiliated to Anna University, popular for its scholarship schemes.',
    website: 'https://www.ssn.edu.in',
    branches: ['Computer Science Engineering', 'Information Technology', 'Electronics & Communication', 'Electrical & Electronics', 'Mechanical Engineering', 'Chemical Engineering']
  },
  {
    name: 'NIT Kurukshetra',
    type: 'NIT',
    nirfRank: 44,
    city: 'Kurukshetra',
    state: 'Haryana',
    admissionMode: 'JEE Mains',
    feesPerYear: 145000,
    cutoffRankCSE: '~12000',
    avgPlacement: 11.2,
    highestPlacement: 43.7,
    description: 'National Institute of Technology Kurukshetra is a premier public engineering university in Haryana, known for its strong technical education standard and coding culture.',
    website: 'http://www.nitkkr.ac.in',
    branches: ['Computer Science Engineering', 'Information Technology', 'Electronics & Communication', 'Electrical Engineering', 'Mechanical Engineering', 'Civil Engineering']
  },
  {
    name: 'NIT Silchar',
    type: 'NIT',
    nirfRank: 45,
    city: 'Silchar',
    state: 'Assam',
    admissionMode: 'JEE Mains',
    feesPerYear: 145000,
    cutoffRankCSE: '~16000',
    avgPlacement: 10.8,
    highestPlacement: 44.0,
    description: 'National Institute of Technology Silchar is one of the premier NITs in northeast India, specializing in high computing research and outstanding placement outputs.',
    website: 'http://www.nits.ac.in',
    branches: ['Computer Science Engineering', 'Electronics & Communication', 'Electrical Engineering', 'Mechanical Engineering', 'Civil Engineering', 'Instrumentation Engineering']
  },
  {
    name: 'NIT Durgapur',
    type: 'NIT',
    nirfRank: 46,
    city: 'Durgapur',
    state: 'West Bengal',
    admissionMode: 'JEE Mains',
    feesPerYear: 145000,
    cutoffRankCSE: '~14000',
    avgPlacement: 9.5,
    highestPlacement: 51.0,
    description: 'National Institute of Technology Durgapur is an Institute of National Importance located in West Bengal, offering core and IT industry-oriented courses.',
    website: 'http://www.nitdgp.ac.in',
    branches: ['Computer Science Engineering', 'Electronics & Communication', 'Electrical Engineering', 'Mechanical Engineering', 'Chemical Engineering', 'Biotechnology']
  },
  {
    name: 'PSG College of Technology',
    type: 'Private',
    nirfRank: 47,
    city: 'Coimbatore',
    state: 'Tamil Nadu',
    admissionMode: 'TNEA',
    feesPerYear: 150000,
    cutoffRankCSE: '~2500',
    avgPlacement: 8.0,
    highestPlacement: 38.0,
    description: 'PSG College of Technology is a government-aided private engineering college in Coimbatore. It has a high reputation for industry-institute collaboration and core placements.',
    website: 'http://www.psgtech.edu',
    branches: ['Computer Science Engineering', 'Information Technology', 'Electronics & Communication', 'Mechanical Engineering', 'Metallurgical Engineering', 'Production Engineering']
  },
  {
    name: 'NIT Jalandhar',
    type: 'NIT',
    nirfRank: 48,
    city: 'Jalandhar',
    state: 'Punjab',
    admissionMode: 'JEE Mains',
    feesPerYear: 145000,
    cutoffRankCSE: '~15000',
    avgPlacement: 9.2,
    highestPlacement: 43.0,
    description: 'Dr. B. R. Ambedkar National Institute of Technology Jalandhar offers high-end technology and science labs, preparing students for success in global IT and manufacturing sectors.',
    website: 'https://www.nitj.ac.in',
    branches: ['Computer Science Engineering', 'Electronics & Communication', 'Electrical Engineering', 'Mechanical Engineering', 'Chemical Engineering', 'Industrial & Production']
  },
  {
    name: 'IIIT Hyderabad',
    type: 'IIIT',
    nirfRank: 49,
    city: 'Hyderabad',
    state: 'Telangana',
    admissionMode: 'JEE Mains / DASA',
    feesPerYear: 360000,
    cutoffRankCSE: '~2000',
    avgPlacement: 26.0,
    highestPlacement: 102.0,
    description: 'International Institute of Information Technology Hyderabad is a prestigious research university. Famous for its competitive programming culture, coding labs, and research output, its average package for CSE is among the highest in India.',
    website: 'https://www.iiit.ac.in',
    branches: ['Computer Science Engineering', 'Electronics & Communication Engineering']
  },
  {
    name: 'IIIT Bangalore',
    type: 'IIIT',
    nirfRank: 50,
    city: 'Bengaluru',
    state: 'Karnataka',
    admissionMode: 'JEE Mains',
    feesPerYear: 400000,
    cutoffRankCSE: '~6000',
    avgPlacement: 24.5,
    highestPlacement: 78.0,
    description: 'International Institute of Information Technology Bangalore is a premier postgraduate and undergraduate institute in the tech-hub of India, known for academic brilliance and rich packages.',
    website: 'https://www.iiitb.ac.in',
    branches: ['Computer Science Engineering', 'Electronics & Communication Engineering']
  },
  {
    name: 'IIIT Delhi',
    type: 'State',
    nirfRank: 51,
    city: 'New Delhi',
    state: 'Delhi',
    admissionMode: 'JAC Delhi / JEE Mains',
    feesPerYear: 400000,
    cutoffRankCSE: '~9000',
    avgPlacement: 18.2,
    highestPlacement: 52.0,
    description: 'Indraprastha Institute of Information Technology Delhi is an autonomous state university in New Delhi with a strong focus on research, computing, and cybersecurity education.',
    website: 'https://www.iiitd.ac.in',
    branches: ['Computer Science Engineering', 'Computer Science & Applied Math', 'Electronics & Communication']
  },
  {
    name: 'IIIT Allahabad',
    type: 'IIIT',
    nirfRank: 52,
    city: 'Prayagraj',
    state: 'Uttar Pradesh',
    admissionMode: 'JEE Mains',
    feesPerYear: 240000,
    cutoffRankCSE: '~5000',
    avgPlacement: 20.8,
    highestPlacement: 102.5,
    description: 'Indian Institute of Information Technology Allahabad is a premier public university known for its robust computing curriculum, competitive coding environment, and top tech placements.',
    website: 'https://www.iiita.ac.in',
    branches: ['Information Technology', 'Electronics & Communication Engineering', 'IT (Specialization in Business Informatics)']
  },
  {
    name: 'NIT Patna',
    type: 'NIT',
    nirfRank: 53,
    city: 'Patna',
    state: 'Bihar',
    admissionMode: 'JEE Mains',
    feesPerYear: 140000,
    cutoffRankCSE: '~18000',
    avgPlacement: 8.8,
    highestPlacement: 43.9,
    description: 'National Institute of Technology Patna is one of the oldest engineering colleges in the state, offering high level tech programs and improving placements.',
    website: 'http://www.nitp.ac.in',
    branches: ['Computer Science Engineering', 'Electronics & Communication', 'Electrical Engineering', 'Mechanical Engineering', 'Civil Engineering']
  },
  {
    name: 'NIT Raipur',
    type: 'NIT',
    nirfRank: 54,
    city: 'Raipur',
    state: 'Chhattisgarh',
    admissionMode: 'JEE Mains',
    feesPerYear: 140000,
    cutoffRankCSE: '~19000',
    avgPlacement: 8.5,
    highestPlacement: 57.5,
    description: 'National Institute of Technology Raipur is located in the industrial capital of Chhattisgarh, offering engineering degrees that are highly valued in public and private sectors.',
    website: 'http://www.nitrr.ac.in',
    branches: ['Computer Science Engineering', 'Information Technology', 'Electronics & Communication', 'Mechanical Engineering', 'Metallurgical Engineering']
  },
  {
    name: 'NIT Jamshedpur',
    type: 'NIT',
    nirfRank: 55,
    city: 'Jamshedpur',
    state: 'Jharkhand',
    admissionMode: 'JEE Mains',
    feesPerYear: 140000,
    cutoffRankCSE: '~12000',
    avgPlacement: 10.9,
    highestPlacement: 83.0,
    description: 'National Institute of Technology Jamshedpur is famous for its placement records in heavy industries and top IT firms, located in the steel city of India.',
    website: 'http://www.nitjsr.ac.in',
    branches: ['Computer Science Engineering', 'Electronics & Communication', 'Electrical Engineering', 'Mechanical Engineering', 'Metallurgical & Materials', 'Civil Engineering']
  },
  {
    name: 'NIT Hamirpur',
    type: 'NIT',
    nirfRank: 56,
    city: 'Hamirpur',
    state: 'Himachal Pradesh',
    admissionMode: 'JEE Mains',
    feesPerYear: 140000,
    cutoffRankCSE: '~22000',
    avgPlacement: 8.1,
    highestPlacement: 112.0,
    description: 'National Institute of Technology Hamirpur boasts a beautiful campus in the Himalayan foothills, offering modern engineering programs and quality placement drives.',
    website: 'http://www.nith.ac.in',
    branches: ['Computer Science Engineering', 'Electronics & Communication', 'Electrical Engineering', 'Mechanical Engineering', 'Chemical Engineering', 'Material Science']
  },
  {
    name: 'NIT Goa',
    type: 'NIT',
    nirfRank: 57,
    city: 'Farmagudi',
    state: 'Goa',
    admissionMode: 'JEE Mains',
    feesPerYear: 140000,
    cutoffRankCSE: '~20000',
    avgPlacement: 9.2,
    highestPlacement: 44.0,
    description: 'National Institute of Technology Goa is a premier public university established in Goa, offering high quality education and strong computing infrastructure.',
    website: 'http://www.nitgoa.ac.in',
    branches: ['Computer Science Engineering', 'Electronics & Communication', 'Electrical & Electronics', 'Mechanical Engineering', 'Civil Engineering']
  },
  {
    name: 'NIT Uttarakhand',
    type: 'NIT',
    nirfRank: 58,
    city: 'Srinagar',
    state: 'Uttarakhand',
    admissionMode: 'JEE Mains',
    feesPerYear: 140000,
    cutoffRankCSE: '~25000',
    avgPlacement: 8.0,
    highestPlacement: 34.0,
    description: 'National Institute of Technology Uttarakhand is situated in the scenic town of Srinagar Garhwal, offering rigorous technical training and rising coding activities.',
    website: 'http://www.nituk.ac.in',
    branches: ['Computer Science Engineering', 'Electronics & Communication', 'Electrical & Electronics', 'Mechanical Engineering', 'Civil Engineering']
  },
  {
    name: 'NIT Manipur',
    type: 'NIT',
    nirfRank: 59,
    city: 'Imphal',
    state: 'Manipur',
    admissionMode: 'JEE Mains',
    feesPerYear: 140000,
    cutoffRankCSE: '~35000',
    avgPlacement: 7.2,
    highestPlacement: 45.0,
    description: 'National Institute of Technology Manipur is an institute of national importance established in the northeastern state, helping students achieve technical proficiency.',
    website: 'http://www.nitmanipur.ac.in',
    branches: ['Computer Science Engineering', 'Electronics & Communication', 'Electrical Engineering', 'Mechanical Engineering', 'Civil Engineering']
  },
  {
    name: 'NSUT Delhi',
    type: 'State',
    nirfRank: 60,
    city: 'New Delhi',
    state: 'Delhi',
    admissionMode: 'JEE Mains',
    feesPerYear: 219000,
    cutoffRankCSE: '~12000',
    avgPlacement: 14.0,
    highestPlacement: 60.0,
    description: 'Netaji Subhas University of Technology (formerly NSIT) is a premier state university in New Delhi. It is renowned for its competitive student cohort and tech company placements.',
    website: 'http://www.nsut.ac.in',
    branches: ['Computer Science Engineering', 'Information Technology', 'Electronics & Communication Engineering', 'Instrumentation & Control Engineering', 'Mechanical Engineering']
  },
  {
    name: 'NIT Meghalaya',
    type: 'NIT',
    nirfRank: 61,
    city: 'Shillong',
    state: 'Meghalaya',
    admissionMode: 'JEE Mains',
    feesPerYear: 140000,
    cutoffRankCSE: '~28000',
    avgPlacement: 8.2,
    highestPlacement: 52.0,
    description: 'National Institute of Technology Meghalaya is situated in the beautiful hill station Shillong, offering quality technical education and robust computer labs.',
    website: 'http://nitmeghalaya.in',
    branches: ['Computer Science Engineering', 'Electronics & Communication', 'Electrical Engineering', 'Mechanical Engineering', 'Civil Engineering']
  },
  {
    name: 'MNIT Jaipur',
    type: 'NIT',
    nirfRank: 62,
    city: 'Jaipur',
    state: 'Rajasthan',
    admissionMode: 'JEE Mains',
    feesPerYear: 145000,
    cutoffRankCSE: '~4500',
    avgPlacement: 12.4,
    highestPlacement: 56.0,
    description: 'Malaviya National Institute of Technology Jaipur is a public university located in the heart of Jaipur. It features a modern green campus and stands out as the premier engineering institute in Rajasthan.',
    website: 'http://www.mnit.ac.in',
    branches: ['Computer Science Engineering', 'Electronics & Communication Engineering', 'Electrical Engineering', 'Mechanical Engineering', 'Chemical Engineering', 'Civil Engineering', 'Metallurgical Engineering']
  },
  {
    name: 'NIT Srinagar',
    type: 'NIT',
    nirfRank: 63,
    city: 'Srinagar',
    state: 'Jammu & Kashmir',
    admissionMode: 'JEE Mains',
    feesPerYear: 140000,
    cutoffRankCSE: '~30000',
    avgPlacement: 7.8,
    highestPlacement: 42.0,
    description: 'National Institute of Technology Srinagar is one of the oldest NITs, situated on the banks of Dal Lake. It offers historic academic legacy and high-quality lab facilities.',
    website: 'http://www.nitsri.ac.in',
    branches: ['Computer Science Engineering', 'Electronics & Communication', 'Electrical Engineering', 'Mechanical Engineering', 'Chemical Engineering', 'Civil Engineering']
  },
  {
    name: 'NIT Agartala',
    type: 'NIT',
    nirfRank: 64,
    city: 'Agartala',
    state: 'Tripura',
    admissionMode: 'JEE Mains',
    feesPerYear: 140000,
    cutoffRankCSE: '~24000',
    avgPlacement: 8.5,
    highestPlacement: 52.0,
    description: 'National Institute of Technology Agartala is a highly progressive NIT in northeast India, boasting a beautiful campus and active tech development initiatives.',
    website: 'https://www.nita.ac.in',
    branches: ['Computer Science Engineering', 'Electronics & Communication', 'Electrical Engineering', 'Mechanical Engineering', 'Chemical Engineering', 'Civil Engineering']
  },
  {
    name: 'MANIT Bhopal',
    type: 'NIT',
    nirfRank: 65,
    city: 'Bhopal',
    state: 'Madhya Pradesh',
    admissionMode: 'JEE Mains',
    feesPerYear: 145000,
    cutoffRankCSE: '~11000',
    avgPlacement: 10.1,
    highestPlacement: 82.0,
    description: 'Maulana Azad National Institute of Technology Bhopal features a huge campus, rich infrastructure, and an active placement cell with partnerships in public and IT domains.',
    website: 'http://www.manit.ac.in',
    branches: ['Computer Science Engineering', 'Electronics & Communication', 'Electrical Engineering', 'Mechanical Engineering', 'Chemical Engineering', 'Civil Engineering']
  },
  {
    name: 'NIT Puducherry',
    type: 'NIT',
    nirfRank: 66,
    city: 'Karaikal',
    state: 'Puducherry',
    admissionMode: 'JEE Mains',
    feesPerYear: 140000,
    cutoffRankCSE: '~22000',
    avgPlacement: 8.0,
    highestPlacement: 42.5,
    description: 'National Institute of Technology Puducherry is a premier public university established in the union territory, showing high growth in computer science education.',
    website: 'http://www.nitpy.ac.in',
    branches: ['Computer Science Engineering', 'Electronics & Communication', 'Electrical & Electronics', 'Mechanical Engineering', 'Civil Engineering']
  },
  {
    name: 'PEC Chandigarh',
    type: 'State',
    nirfRank: 67,
    city: 'Chandigarh',
    state: 'Chandigarh',
    admissionMode: 'JEE Mains',
    feesPerYear: 175000,
    cutoffRankCSE: '~15000',
    avgPlacement: 10.8,
    highestPlacement: 64.5,
    description: 'Punjab Engineering College is a historic state-funded engineering university in Chandigarh, highly recognized for producing prominent global business leaders.',
    website: 'https://pec.ac.in',
    branches: ['Computer Science Engineering', 'Electronics & Communication', 'Electrical Engineering', 'Mechanical Engineering', 'Aeronautical Engineering']
  },
  {
    name: 'BMS College of Engineering',
    type: 'Private',
    nirfRank: 68,
    city: 'Bengaluru',
    state: 'Karnataka',
    admissionMode: 'COMEDK / KCET',
    feesPerYear: 220000,
    cutoffRankCSE: '~1200',
    avgPlacement: 8.2,
    highestPlacement: 48.0,
    description: 'B.M.S. College of Engineering is one of the oldest private-aided engineering colleges in India, boasting massive alumni networks in Silicon Valley and Bangalore.',
    website: 'https://bmsce.ac.in',
    branches: ['Computer Science Engineering', 'Information Science Engineering', 'Electronics & Communication', 'Mechanical Engineering', 'Electrical & Electronics']
  },
  {
    name: 'MSRIT Bengaluru',
    type: 'Private',
    nirfRank: 69,
    city: 'Bengaluru',
    state: 'Karnataka',
    admissionMode: 'COMEDK / KCET',
    feesPerYear: 220000,
    cutoffRankCSE: '~1500',
    avgPlacement: 8.5,
    highestPlacement: 46.0,
    description: 'M. S. Ramaiah Institute of Technology is a highly sought-after private engineering college affiliated to VTU, offering stellar computing placement rates.',
    website: 'https://www.msrit.edu',
    branches: ['Computer Science Engineering', 'Information Science Engineering', 'Electronics & Communication', 'Electrical & Electronics', 'Mechanical Engineering']
  },
  {
    name: 'CEG Guindy',
    type: 'State',
    nirfRank: 70,
    city: 'Chennai',
    state: 'Tamil Nadu',
    admissionMode: 'TNEA',
    feesPerYear: 45000,
    cutoffRankCSE: '~500',
    avgPlacement: 8.5,
    highestPlacement: 36.0,
    description: 'College of Engineering, Guindy is one of the oldest engineering institutions in Asia, operating under Anna University, offering highly subsidized fees and great core placements.',
    website: 'https://ceg.annauniv.edu',
    branches: ['Computer Science Engineering', 'Electronics & Communication', 'Electrical & Electronics', 'Mechanical Engineering', 'Information Technology']
  },
  {
    name: 'MIT Chennai',
    type: 'State',
    nirfRank: 71,
    city: 'Chennai',
    state: 'Tamil Nadu',
    admissionMode: 'TNEA',
    feesPerYear: 45000,
    cutoffRankCSE: '~1000',
    avgPlacement: 7.8,
    highestPlacement: 32.0,
    description: 'Madras Institute of Technology is a premier engineering campus under Anna University, famous for its aerospace engineering department and notable alumni like Dr. A.P.J. Abdul Kalam.',
    website: 'https://mitindia.edu',
    branches: ['Computer Science Engineering', 'Aeronautical Engineering', 'Electronics & Communication', 'Information Technology', 'Automobile Engineering']
  },
  {
    name: 'IIIT Gwalior',
    type: 'IIIT',
    nirfRank: 72,
    city: 'Gwalior',
    state: 'Madhya Pradesh',
    admissionMode: 'JEE Mains',
    feesPerYear: 180000,
    cutoffRankCSE: '~8000',
    avgPlacement: 15.6,
    highestPlacement: 59.2,
    description: 'Atal Bihari Vajpayee Indian Institute of Information Technology and Management Gwalior is a premier public university specializing in IT and management education.',
    website: 'https://www.iiitm.ac.in',
    branches: ['Computer Science Engineering', 'Information Technology', 'Integrated M.Tech (IT)']
  },
  {
    name: 'COEP Tech',
    type: 'State',
    nirfRank: 73,
    city: 'Pune',
    state: 'Maharashtra',
    admissionMode: 'MHT-CET',
    feesPerYear: 135000,
    cutoffRankCSE: '~200 (Score)',
    avgPlacement: 9.8,
    highestPlacement: 50.0,
    description: 'College of Engineering Pune (COEP) is one of the oldest engineering colleges in Asia. Highly esteemed in Maharashtra, it has a legacy of excellence and outstanding industrial connections in Pune.',
    website: 'https://www.coep.org.in',
    branches: ['Computer Science Engineering', 'Electronics & Telecommunication', 'Electrical Engineering', 'Mechanical Engineering', 'Production Engineering', 'Civil Engineering']
  },
  {
    name: 'IIIT Jabalpur',
    type: 'IIIT',
    nirfRank: 74,
    city: 'Jabalpur',
    state: 'Madhya Pradesh',
    admissionMode: 'JEE Mains',
    feesPerYear: 160000,
    cutoffRankCSE: '~14000',
    avgPlacement: 13.9,
    highestPlacement: 82.0,
    description: 'PDPM Indian Institute of Information Technology, Design and Manufacturing Jabalpur integrates IT, design, and manufacturing in its engineering courses.',
    website: 'https://www.iiitdmj.ac.in',
    branches: ['Computer Science Engineering', 'Smart Manufacturing', 'Electronics & Communication', 'Mechanical Engineering']
  },
  {
    name: 'IIIT Kancheepuram',
    type: 'IIIT',
    nirfRank: 75,
    city: 'Kancheepuram',
    state: 'Tamil Nadu',
    admissionMode: 'JEE Mains',
    feesPerYear: 160000,
    cutoffRankCSE: '~18000',
    avgPlacement: 10.2,
    highestPlacement: 42.0,
    description: 'Indian Institute of Information Technology, Design and Manufacturing, Kancheepuram is established by the Ministry of Education to promote design-centric engineering.',
    website: 'https://www.iiitdm.ac.in',
    branches: ['Computer Science Engineering', 'Electronics & Communication (Design)', 'Mechanical Engineering (Design)']
  },
  {
    name: 'IIIT Lucknow',
    type: 'IIIT',
    nirfRank: 76,
    city: 'Lucknow',
    state: 'Uttar Pradesh',
    admissionMode: 'JEE Mains',
    feesPerYear: 220000,
    cutoffRankCSE: '~11000',
    avgPlacement: 14.5,
    highestPlacement: 59.0,
    description: 'Indian Institute of Information Technology Lucknow has emerged as one of the fastest growing IIITs, offering exceptional tech placements and coding environments.',
    website: 'https://www.iiitl.ac.in',
    branches: ['Computer Science Engineering', 'Information Technology', 'Computer Science & Business']
  },
  {
    name: 'IIIT Sri City',
    type: 'IIIT',
    nirfRank: 77,
    city: 'Sri City',
    state: 'Andhra Pradesh',
    admissionMode: 'JEE Mains',
    feesPerYear: 250000,
    cutoffRankCSE: '~22000',
    avgPlacement: 12.0,
    highestPlacement: 85.0,
    description: 'Indian Institute of Information Technology Sri City is located in a smart industrial city, facilitating strong industry internships and computing research.',
    website: 'https://www.iiits.ac.in',
    branches: ['Computer Science Engineering', 'Electronics & Communication Engineering']
  },
  {
    name: 'IIT Tirupati',
    type: 'IIT',
    nirfRank: 78,
    city: 'Tirupati',
    state: 'Andhra Pradesh',
    admissionMode: 'JEE Advanced',
    feesPerYear: 220000,
    cutoffRankCSE: '~10000',
    avgPlacement: 11.5,
    highestPlacement: 40.0,
    description: 'Indian Institute of Technology Tirupati is a third-generation IIT that features modern labs and a rapidly growing academic curriculum.',
    website: 'https://iittp.ac.in',
    branches: ['Computer Science Engineering', 'Electrical Engineering', 'Mechanical Engineering', 'Civil Engineering', 'Chemical Engineering']
  },
  {
    name: 'IIT Palakkad',
    type: 'IIT',
    nirfRank: 79,
    city: 'Palakkad',
    state: 'Kerala',
    admissionMode: 'JEE Advanced',
    feesPerYear: 220000,
    cutoffRankCSE: '~11000',
    avgPlacement: 11.2,
    highestPlacement: 41.5,
    description: 'Indian Institute of Technology Palakkad offers quality education and state-of-the-art laboratory research facilities in the scenic state of Kerala.',
    website: 'https://iitpkd.ac.in',
    branches: ['Computer Science Engineering', 'Electrical Engineering', 'Mechanical Engineering', 'Civil Engineering']
  },
  {
    name: 'IIT Dharwad',
    type: 'IIT',
    nirfRank: 80,
    city: 'Dharwad',
    state: 'Karnataka',
    admissionMode: 'JEE Advanced',
    feesPerYear: 220000,
    cutoffRankCSE: '~12000',
    avgPlacement: 10.8,
    highestPlacement: 38.0,
    description: 'Indian Institute of Technology Dharwad is a public research university in Karnataka, known for industrial mentorship programs and growing computing capabilities.',
    website: 'https://iitdh.ac.in',
    branches: ['Computer Science Engineering', 'Electrical Engineering', 'Mechanical Engineering', 'Engineering Physics']
  },
  {
    name: 'IIT Bhilai',
    type: 'IIT',
    nirfRank: 81,
    city: 'Bhilai',
    state: 'Chhattisgarh',
    admissionMode: 'JEE Advanced',
    feesPerYear: 220000,
    cutoffRankCSE: '~12500',
    avgPlacement: 11.0,
    highestPlacement: 42.0,
    description: 'Indian Institute of Technology Bhilai is an institute of national importance established in Chhattisgarh, providing advanced courses in data science and computer engineering.',
    website: 'https://iitbhilai.ac.in',
    branches: ['Computer Science Engineering', 'Electrical Engineering', 'Mechanical Engineering', 'Data Science & Artificial Intelligence']
  },
  {
    name: 'IIT Goa',
    type: 'IIT',
    nirfRank: 82,
    city: 'Ponda',
    state: 'Goa',
    admissionMode: 'JEE Advanced',
    feesPerYear: 220000,
    cutoffRankCSE: '~11000',
    avgPlacement: 12.0,
    highestPlacement: 60.0,
    description: 'Indian Institute of Technology Goa is a premier public university established in Goa, offering high quality education and strong computing research opportunities.',
    website: 'https://iitgoa.ac.in',
    branches: ['Computer Science Engineering', 'Electrical Engineering', 'Mechanical Engineering', 'Mathematics and Computing']
  },
  {
    name: 'IIT Jammu',
    type: 'IIT',
    nirfRank: 83,
    city: 'Jammu',
    state: 'Jammu & Kashmir',
    admissionMode: 'JEE Advanced',
    feesPerYear: 220000,
    cutoffRankCSE: '~13000',
    avgPlacement: 10.5,
    highestPlacement: 45.0,
    description: 'Indian Institute of Technology Jammu is located in the union territory of Jammu and Kashmir, featuring high level tech training labs and rising tech startups.',
    website: 'https://iitjammu.ac.in',
    branches: ['Computer Science Engineering', 'Electrical Engineering', 'Mechanical Engineering', 'Civil Engineering', 'Materials Engineering']
  },
  {
    name: 'BITS Goa',
    type: 'BITS',
    nirfRank: 84,
    city: 'Zuarinagar',
    state: 'Goa',
    admissionMode: 'BITSAT',
    feesPerYear: 520000,
    cutoffRankCSE: '~280',
    avgPlacement: 15.1,
    highestPlacement: 90.0,
    description: 'BITS Pilani K.K. Birla Goa Campus is one of the three campuses of BITS Pilani. Situated in a scenic location in Goa, it offers top-notch academic parity and practice school placements on par with Pilani.',
    website: 'https://www.bits-pilani.ac.in/goa/',
    branches: ['Computer Science Engineering', 'Electrical & Electronics Engineering', 'Electronics & Instrumentation', 'Mechanical Engineering', 'Chemical Engineering']
  },
  {
    name: 'BITS Hyderabad',
    type: 'BITS',
    nirfRank: 85,
    city: 'Jawaharnagar',
    state: 'Telangana',
    admissionMode: 'BITSAT',
    feesPerYear: 520000,
    cutoffRankCSE: '~270',
    avgPlacement: 14.8,
    highestPlacement: 85.0,
    description: 'BITS Pilani Hyderabad Campus is one of the premier campuses of BITS. It has exceptional research facilities and provides students with opportunities in IT, VLSI, and core sectors.',
    website: 'https://www.bits-pilani.ac.in/hyderabad/',
    branches: ['Computer Science Engineering', 'Electrical & Electronics Engineering', 'Electronics & Communication', 'Mechanical Engineering', 'Chemical Engineering']
  },
  {
    name: 'VIT Chennai',
    type: 'VIT',
    nirfRank: 86,
    city: 'Chennai',
    state: 'Tamil Nadu',
    admissionMode: 'VITEEE',
    feesPerYear: 195000,
    cutoffRankCSE: '~12000',
    avgPlacement: 7.2,
    highestPlacement: 40.0,
    description: 'Vellore Institute of Technology Chennai Campus is a private campus of VIT offering great infrastructure, flexibility via the Fully Flexible Credit System (FFCS), and centralized placement opportunities with Vellore.',
    website: 'https://chennai.vit.ac.in',
    branches: ['Computer Science Engineering', 'Electronics & Communication Engineering', 'Electrical & Electronics Engineering', 'Mechanical Engineering', 'Civil Engineering']
  },
  {
    name: 'VIT Bhopal',
    type: 'VIT',
    nirfRank: 87,
    city: 'Bhopal',
    state: 'Madhya Pradesh',
    admissionMode: 'VITEEE',
    feesPerYear: 195000,
    cutoffRankCSE: '~22000',
    avgPlacement: 6.8,
    highestPlacement: 41.2,
    description: 'VIT Bhopal University offers futuristic technology learning with its CALTech (Collaborative Active Learning through Technology) methodology and excellent placements.',
    website: 'https://vitbhopal.ac.in',
    branches: ['Computer Science Engineering', 'Cyber Security & Forensic', 'AI & Machine Learning', 'Electronics & Communication']
  },
  {
    name: 'VIT AP',
    type: 'VIT',
    nirfRank: 88,
    city: 'Amaravati',
    state: 'Andhra Pradesh',
    admissionMode: 'VITEEE',
    feesPerYear: 195000,
    cutoffRankCSE: '~20000',
    avgPlacement: 6.9,
    highestPlacement: 34.4,
    description: 'VIT AP University offers a highly interactive learning atmosphere and shared centralized placements with VIT Vellore, located in the capital region of Andhra Pradesh.',
    website: 'https://vitap.ac.in',
    branches: ['Computer Science Engineering', 'Computer Science & Business Systems', 'Data Analytics', 'Electronics & Communication']
  },
  {
    name: 'RV College of Engineering',
    type: 'Private',
    nirfRank: 89,
    city: 'Bengaluru',
    state: 'Karnataka',
    admissionMode: 'COMEDK',
    feesPerYear: 250000,
    cutoffRankCSE: '~300',
    avgPlacement: 11.2,
    highestPlacement: 53.0,
    description: 'Rashtreeya Vidyalaya College of Engineering is a private technical institution in Bengaluru. It is regarded as the top private college under COMEDK, offering prime placements in the Silicon Valley of India.',
    website: 'https://rvce.edu.in',
    branches: ['Computer Science Engineering', 'Information Science Engineering', 'Electronics & Communication Engineering', 'Mechanical Engineering', 'Electrical & Electronics Engineering']
  },
  {
    name: 'LNMIIT Jaipur',
    type: 'Private',
    nirfRank: 90,
    city: 'Jaipur',
    state: 'Rajasthan',
    admissionMode: 'JEE Mains',
    feesPerYear: 320000,
    cutoffRankCSE: '~35000',
    avgPlacement: 13.5,
    highestPlacement: 50.6,
    description: 'LNM Institute of Information Technology is a public-private partnership deemed university in Jaipur, focused on IT and communication sectors with highly notable packages.',
    website: 'https://www.lnmiit.ac.in',
    branches: ['Computer Science Engineering', 'Communication & Computer Engineering', 'Electronics & Communication', 'Mechanical Engineering']
  },
  {
    name: 'Nirma University',
    type: 'Private',
    nirfRank: 91,
    city: 'Ahmedabad',
    state: 'Gujarat',
    admissionMode: 'JEE Mains / GUJCET',
    feesPerYear: 200000,
    cutoffRankCSE: '~3000',
    avgPlacement: 7.8,
    highestPlacement: 88.2,
    description: 'Nirma University is a prominent private university in Gujarat, offering standard academic courses and active coding societies.',
    website: 'https://nirmauni.ac.in',
    branches: ['Computer Science Engineering', 'Electronics & Communication', 'Chemical Engineering', 'Mechanical Engineering', 'Civil Engineering']
  },
  {
    name: 'KJ Somaiya College',
    type: 'Private',
    nirfRank: 92,
    city: 'Mumbai',
    state: 'Maharashtra',
    admissionMode: 'MHT-CET / JEE / SAT',
    feesPerYear: 350000,
    cutoffRankCSE: '~1500',
    avgPlacement: 7.2,
    highestPlacement: 40.0,
    description: 'K. J. Somaiya College of Engineering is a prominent private autonomous engineering college in Mumbai, offering a large green campus and extensive project opportunities.',
    website: 'https://kjsce.somaiya.edu',
    branches: ['Computer Science Engineering', 'Information Technology', 'Electronics & Telecommunication', 'Mechanical Engineering']
  },
  {
    name: 'DJSCE Mumbai',
    type: 'Private',
    nirfRank: 93,
    city: 'Mumbai',
    state: 'Maharashtra',
    admissionMode: 'MHT-CET / JEE',
    feesPerYear: 190000,
    cutoffRankCSE: '~800',
    avgPlacement: 8.5,
    highestPlacement: 45.0,
    description: 'Dwarkadas J. Sanghvi College of Engineering is a top-ranked private engineering institute in Mumbai, highly known for its tech placement ratios.',
    website: 'https://www.djsce.ac.in',
    branches: ['Computer Engineering', 'Information Technology', 'Electronics & Telecommunication', 'Mechanical Engineering', 'Data Engineering']
  },
  {
    name: 'VJTI Mumbai',
    type: 'State',
    nirfRank: 94,
    city: 'Mumbai',
    state: 'Maharashtra',
    admissionMode: 'MHT-CET',
    feesPerYear: 85000,
    cutoffRankCSE: '~150',
    avgPlacement: 12.0,
    highestPlacement: 62.0,
    description: 'Veermata Jijabai Technological Institute is a premier state-funded institute in Mumbai, boasting a massive legacy of producing tech leaders and core engineering experts.',
    website: 'https://vjti.ac.in',
    branches: ['Computer Engineering', 'Information Technology', 'Electronics Engineering', 'Electrical Engineering', 'Mechanical Engineering', 'Production Engineering']
  },
  {
    name: 'SPIT Mumbai',
    type: 'Private',
    nirfRank: 95,
    city: 'Mumbai',
    state: 'Maharashtra',
    admissionMode: 'MHT-CET / JEE',
    feesPerYear: 170000,
    cutoffRankCSE: '~400',
    avgPlacement: 11.5,
    highestPlacement: 42.0,
    description: 'Sardar Patel Institute of Technology is a highly rated private engineering college in Mumbai, offering top-notch coding bootcamps and strong corporate associations.',
    website: 'https://www.spit.ac.in',
    branches: ['Computer Engineering', 'Information Technology', 'Computer Science & Enterprise', 'Electronics & Telecommunication']
  },
  {
    name: 'JECRC University',
    type: 'Private',
    nirfRank: 96,
    city: 'Jaipur',
    state: 'Rajasthan',
    admissionMode: 'Merit / JEE',
    feesPerYear: 150000,
    cutoffRankCSE: '~85% Marks',
    avgPlacement: 5.5,
    highestPlacement: 44.0,
    description: 'JECRC University is a private university in Jaipur, Rajasthan, known for its focus on industrial partnerships, coding platforms, and massive pool placement drives.',
    website: 'https://jecrcuniversity.edu.in',
    branches: ['Computer Science Engineering', 'AI & Machine Learning', 'Electronics & Communication Engineering', 'Mechanical Engineering', 'Civil Engineering']
  },
  {
    name: 'SKIT Jaipur',
    type: 'State',
    nirfRank: 97,
    city: 'Jaipur',
    state: 'Rajasthan',
    admissionMode: 'REAP / JEE',
    feesPerYear: 85000,
    cutoffRankCSE: '~350000',
    avgPlacement: 4.8,
    highestPlacement: 22.0,
    description: 'Swami Keshvanand Institute of Technology, Management & Gramothan is affiliated with RTU. It is ranked as the top private college affiliated with Rajasthan Technical University, offering strong local placements.',
    website: 'https://www.skit.ac.in',
    branches: ['Computer Science Engineering', 'Information Technology', 'Electronics & Communication Engineering', 'Electrical Engineering', 'Mechanical Engineering', 'Civil Engineering']
  },
  {
    name: 'Poornima College of Engineering',
    type: 'State',
    nirfRank: 98,
    city: 'Jaipur',
    state: 'Rajasthan',
    admissionMode: 'REAP / JEE',
    feesPerYear: 85000,
    cutoffRankCSE: '~400000',
    avgPlacement: 4.5,
    highestPlacement: 20.0,
    description: 'Poornima College of Engineering is a prominent private engineering college in Jaipur, affiliated with RTU. It focuses heavily on tech training and holds massive campus placement drives.',
    website: 'https://www.poornima.org',
    branches: ['Computer Science Engineering', 'Artificial Intelligence', 'Electronics & Communication Engineering', 'Mechanical Engineering', 'Civil Engineering']
  },
  {
    name: 'Arya Institute of Engineering & Technology',
    type: 'State',
    nirfRank: 99,
    city: 'Jaipur',
    state: 'Rajasthan',
    admissionMode: 'REAP / JEE',
    feesPerYear: 80000,
    cutoffRankCSE: '~450000',
    avgPlacement: 4.2,
    highestPlacement: 18.0,
    description: 'Arya Group of Colleges (Main Campus - AIET) is a well-known engineering college in Jaipur. Known for its robotics labs and local placements, it serves a large student body in Rajasthan.',
    website: 'https://www.aryacollege.in',
    branches: ['Computer Science Engineering', 'Information Technology', 'Electronics & Communication Engineering', 'Electrical Engineering', 'Mechanical Engineering']
  },
  {
    name: 'Graphic Era University',
    type: 'Private',
    nirfRank: 100,
    city: 'Dehradun',
    state: 'Uttarakhand',
    admissionMode: 'Merit / JEE',
    feesPerYear: 280000,
    cutoffRankCSE: '~80% Marks',
    avgPlacement: 6.2,
    highestPlacement: 48.5,
    description: 'Graphic Era Deemed to be University is a private university in Uttarakhand, offering engineering programs with scenic mountain views and a high rate of corporate recruitment.',
    website: 'https://www.geu.ac.in',
    branches: ['Computer Science Engineering', 'Information Technology', 'Electronics & Communication', 'Mechanical Engineering', 'Biotechnology']
  }
];

const seedDB = async () => {
  try {
    const mongoUri = process.env.MONGODB_URI || 'mongodb://localhost:27017/btechhelpline';
    await mongoose.connect(mongoUri);
    console.log('MongoDB Connected for Seeding...');

    // Clear existing colleges
    await College.deleteMany({});
    console.log('Cleared existing colleges.');

    // Insert new colleges
    await College.insertMany(colleges);
    console.log(`Successfully seeded ${colleges.length} colleges!`);

    mongoose.connection.close();
    process.exit(0);
  } catch (error) {
    console.error('Seeding error:', error);
    process.exit(1);
  }
};

seedDB();
